name: "Mark WASM as Current"
description: "Touch WASM artifacts to mark them as up-to-date and invalidate caches if artifacts changed"

runs:
  using: "composite"
  steps:
    - name: Mark WASM as up-to-date
      shell: bash
      run: |
        # Touch WASM artifacts to be newer than sources so mise skips rebuild
        touch crates/eryx-runtime/runtime.wasm crates/eryx-runtime/runtime.cwasm

        # Touch prebuilt artifacts if they exist
        if [ -d crates/eryx-runtime/prebuilt ]; then
          touch crates/eryx-runtime/prebuilt/*
        fi

        # Check if prebuilt artifacts changed by comparing checksums
        # This is critical: eryx-runtime's build.rs caches .so.zst files in OUT_DIR
        # If the prebuilt artifacts changed (e.g., new WIT interface), we must
        # invalidate the cached OUT_DIR artifacts so the new ones get copied
        PREBUILT_HASH=""
        if [ -f crates/eryx-runtime/prebuilt/liberyx_runtime.so.zst ]; then
          PREBUILT_HASH=$(sha256sum crates/eryx-runtime/prebuilt/liberyx_runtime.so.zst crates/eryx-runtime/prebuilt/liberyx_bindings.so.zst 2>/dev/null | sha256sum | cut -d' ' -f1)
        fi
        CACHED_PREBUILT_HASH=""
        if [ -f target/.prebuilt-hash ]; then
          CACHED_PREBUILT_HASH=$(cat target/.prebuilt-hash)
        fi

        if [ -n "$PREBUILT_HASH" ] && [ "$PREBUILT_HASH" != "$CACHED_PREBUILT_HASH" ]; then
          echo "Prebuilt artifacts changed ($CACHED_PREBUILT_HASH -> $PREBUILT_HASH)"
          echo "Invalidating eryx-runtime OUT_DIR caches..."
          # Remove all cached .so.zst files from eryx-runtime OUT_DIRs
          # These live in target/*/build/eryx-runtime-*/out/
          find target -path "*/build/eryx-runtime-*/out/*.so.zst" -delete 2>/dev/null || true
          # Also touch eryx-runtime's build.rs to force rebuild
          touch crates/eryx-runtime/build.rs
          mkdir -p target
          echo "$PREBUILT_HASH" > target/.prebuilt-hash
        else
          echo "Prebuilt artifacts unchanged"
        fi

        # Check if cwasm changed by comparing checksums
        # This invalidates cached binaries that have old cwasm embedded
        CWASM_HASH=$(sha256sum crates/eryx-runtime/runtime.cwasm | cut -d' ' -f1)
        CACHED_HASH=""
        if [ -f target/.cwasm-hash ]; then
          CACHED_HASH=$(cat target/.cwasm-hash)
        fi

        if [ "$CWASM_HASH" != "$CACHED_HASH" ]; then
          echo "cwasm changed ($CACHED_HASH -> $CWASM_HASH), invalidating embedded.rs"
          touch crates/eryx/src/embedded.rs
          mkdir -p target
          echo "$CWASM_HASH" > target/.cwasm-hash
        else
          echo "cwasm unchanged ($CWASM_HASH)"
        fi

        # Check if WIT interface changed by comparing checksums
        # This invalidates cached bindings generated by wasmtime::component::bindgen!
        # The bindgen! macro reads the WIT file at compile time, but Cargo doesn't
        # track it as a dependency, so we must manually invalidate wasm.rs
        WIT_HASH=$(sha256sum crates/eryx-runtime/wit/runtime.wit | cut -d' ' -f1)
        CACHED_WIT_HASH=""
        if [ -f target/.wit-hash ]; then
          CACHED_WIT_HASH=$(cat target/.wit-hash)
        fi

        if [ "$WIT_HASH" != "$CACHED_WIT_HASH" ]; then
          echo "WIT interface changed ($CACHED_WIT_HASH -> $WIT_HASH), invalidating wasm.rs bindings"
          touch crates/eryx/src/wasm.rs
          mkdir -p target
          echo "$WIT_HASH" > target/.wit-hash
        else
          echo "WIT interface unchanged ($WIT_HASH)"
        fi
